# Generated by Django 4.2.1 on 2023-05-22 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='reasonforappointment',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='diagnosis',
            field=models.TextField(default='No diagnosis entered yet'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='prescription',
            field=models.TextField(default='No diagnosis entered yet'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='symptoms',
            field=models.TextField(default='No symptoms entered yet'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
