# Generated by Django 4.2.1 on 2023-05-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0005_remove_patient_name_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
