# Generated by Django 4.2.1 on 2023-05-23 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hms_app', '0008_alter_appointments_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointments',
            name='reasonforappointment',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointments',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
